<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ _sc-eqIVtm fYABJt</name>
   <tag></tag>
   <elementGuidId>966c744b-66a8-442a-9e22-2f37af8378ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;root&quot;]/div[1]/div/div[2]/div/div[3]/div[2]/div[7]/div/div[2]/div/div/div/div/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.sc-eqIVtm.fYABJt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Введите название тренировки</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-eqIVtm fYABJt</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-keGeJD fILytY&quot;]/div[@class=&quot;sc-cHGsZl iheGMK ChessTemplate&quot;]/div[@class=&quot;sc-kgAjT gLMBNJ Right&quot;]/div[@class=&quot;sc-eJbUEs eRKPFJ&quot;]/div[@class=&quot;sc-cTbcWX hHxGLI&quot;]/div[@class=&quot;sc-cstzgH lkdDNC&quot;]/div[@class=&quot;sc-cbKXXB dELshP&quot;]/div[@class=&quot;sc-fjmCvl kCgmGD Wrapper&quot;]/div[@class=&quot;Tab&quot;]/div[@class=&quot;sc-dTdPqK iIYbYs ContentPlaceholder&quot;]/div[@class=&quot;sc-bPPwis htMyAt&quot;]/div[@class=&quot;sc-edbWYL gkCPdP&quot;]/div[@class=&quot;sc-jWNpPo jSdxFS TrainingPlansWrapper&quot;]/div[@class=&quot;sc-jjbLbC hzMDNS TrainingPlansContainer&quot;]/div[@class=&quot;sc-lhyKYM gRXSwE Plan&quot;]/div[@class=&quot;sc-hnKQEj iaFFIf&quot;]/input[@class=&quot;sc-eqIVtm fYABJt&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div[2]/div[2]/div[7]/div/div[2]/div/div/div/div/div/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/input</value>
   </webElementXpaths>
</WebElementEntity>
