<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_- _customQuantity</name>
   <tag></tag>
   <elementGuidId>f9b7abc5-6590-4ed8-b5f2-c050fb05166e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='customQuantity']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;customQuantity&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customQuantity</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_-_-src-components-componentKit-___inputProfile__inputField___2GjT_ _-_-src-___index2__input__field___1bjW9 _-_-src-modules-Mlm-MlmPoints-___style__purchase__card-input___aAe46</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>7</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layout&quot;)/div[@class=&quot;_-_-src-components-componentKit2-___layout__layoutInner___3qSRs _-_-src-___index2__layout__inner___Mts3C undefined&quot;]/div[@class=&quot;_-_-src-components-componentKit2-___layout__grid___3tN4B _-_-src-___index2__grid___2FOUr&quot;]/div[@class=&quot;_-_-src-components-componentKit2-___layout__gridCellLayoutContentPocket34___3K3vW _-_-src-components-componentKit2-___layout__width75___dUSvB _-_-src-___index2__grid__cell___3sCh5&quot;]/div[@class=&quot;_-_-src-components-componentKit2-___layout__layoutWrap___I17Wy _-_-src-components-componentKit2-___layout__layoutWrapSmm___Rc2mr&quot;]/div[1]/div[@class=&quot;_-_-src-modules-Mlm-MlmPoints-___style__mlmSummary___2qtFI&quot;]/div[2]/div[@class=&quot;_-_-src-modules-Mlm-MlmPoints-___style__pointsToBuy___3Q74U&quot;]/div[1]/div[@class=&quot;_-_-src-modules-Mlm-MlmPoints-___style__purchase__card___1cDHS&quot;]/div[@class=&quot;_-_-src-modules-Mlm-MlmPoints-___style__puchase__customQuantity___1xOE0&quot;]/div[@class=&quot;_-_-src-modules-Mlm-MlmPoints-___style__inputWrapper___3XvT0&quot;]/div[@class=&quot;_-_-src-components-componentKit-___inputProfile__inputBox___2ticz _-_-src-___index__input___1sucD _-_-src-___index__input--box___2L6Ex&quot;]/input[@class=&quot;_-_-src-components-componentKit-___inputProfile__inputField___2GjT_ _-_-src-___index2__input__field___1bjW9 _-_-src-modules-Mlm-MlmPoints-___style__purchase__card-input___aAe46&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='customQuantity']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout']/div[2]/div/div[2]/div/div/div/div[2]/div/div/div[2]/div[2]/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
   </webElementXpaths>
</WebElementEntity>
