<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_      ..          .       3E MED    -</name>
   <tag></tag>
   <elementGuidId>3dff4c72-e39b-4bf1-a23e-3ef8a132b9f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='layout']/div[2]/div/div[2]/div/div/div[2]/div/div/div/label/div[2]/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p._-_-src-modules-Mlm-MlmPoints-___style__purchase__card-descr___32RWb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_-_-src-modules-Mlm-MlmPoints-___style__purchase__card-descr___32RWb</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Вы можете приобрести баллы с помощью Яндекс.Кассы. Для этого необходимо прикрепить к данному сервису свою банковскую карту. И для совершения покупки в системе 3E MED выберите вариант оплаты - “Яндекс.Касса”. </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layout&quot;)/div[@class=&quot;_-_-src-components-componentKit2-___layout__layoutInner___3qSRs _-_-src-___index2__layout__inner___Mts3C undefined&quot;]/div[@class=&quot;_-_-src-components-componentKit2-___layout__grid___3tN4B _-_-src-___index2__grid___2FOUr&quot;]/div[@class=&quot;_-_-src-components-componentKit2-___layout__gridCellLayoutContentPocket34___3K3vW _-_-src-components-componentKit2-___layout__width75___dUSvB _-_-src-___index2__grid__cell___3sCh5&quot;]/div[@class=&quot;_-_-src-components-componentKit2-___layout__layoutWrap___I17Wy _-_-src-components-componentKit2-___layout__layoutWrapSmm___Rc2mr&quot;]/div[1]/div[@class=&quot;_-_-src-modules-Mlm-MlmPoints-___style__mlmSummary___2qtFI&quot;]/div[1]/div[@class=&quot;_-_-src-modules-Mlm-MlmPoints-___style__purchaseWays___RwLZS&quot;]/div[@class=&quot;_-_-src-modules-Mlm-MlmPoints-___style__purchaseCardsWrapper___1wuZG&quot;]/label[@class=&quot;_-_-src-modules-Mlm-MlmPoints-___style__purchase__card___1cDHS _-_-src-modules-Mlm-MlmPoints-___style__purchase__card-label___195vx&quot;]/div[@class=&quot;_-_-src-modules-Mlm-MlmPoints-___style__purchase__card-content___1Qc7p&quot;]/p[@class=&quot;_-_-src-modules-Mlm-MlmPoints-___style__purchase__card-descr___32RWb&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout']/div[2]/div/div[2]/div/div/div[2]/div/div/div/label/div[2]/p</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Покупка через Яндекс Кассу'])[1]/following::p[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Способ покупки'])[1]/following::p[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Покупка через Stripe'])[1]/preceding::p[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Вы можете приобрести баллы с помощью Яндекс.Кассы. Для этого необходимо прикрепить к данному сервису свою банковскую карту. И для совершения покупки в системе 3E MED выберите вариант оплаты - “Яндекс.Касса”.']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
   </webElementXpaths>
</WebElementEntity>
