<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>xarakteristika</name>
   <tag></tag>
   <elementGuidId>3ac6c128-0c25-49ea-a6e9-0e77c22873f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='Экстраверсия']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.styles__SkillName-sc-8xsnvi-9.fxKVA</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles__SkillName-sc-8xsnvi-9 fxKVA</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Экстраверсия</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-tabs-1-panel-1&quot;)/div[@class=&quot;styles__TableContent-sc-8xsnvi-1 jMvDNh&quot;]/div[@class=&quot;styles__TableBody-sc-8xsnvi-20 ckquqP&quot;]/div[@class=&quot;styles__TableRow-sc-8xsnvi-15 djWEMP&quot;]/div[@class=&quot;styles__Half-sc-8xsnvi-7 eVRgs&quot;]/div[@class=&quot;styles__IndividualPlanCard-sc-8xsnvi-19 jfxeMa&quot;]/div[@class=&quot;styles__TableRow-sc-8xsnvi-15 djWEMP&quot;]/div[@class=&quot;styles__TableColumn-sc-8xsnvi-14 ktAGVd&quot;]/p[@class=&quot;styles__SkillName-sc-8xsnvi-9 fxKVA&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-tabs-1-panel-1']/div[2]/div[2]/div/div/div/div/div[2]/p[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Индивидуально-типологический'])[1]/following::p[17]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Психологический'])[1]/following::p[17]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Редактирование профиля'])[1]/preceding::p[29]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Экстраверсия']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/p[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Экстраверсия' or . = 'Экстраверсия')]</value>
   </webElementXpaths>
</WebElementEntity>
