<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__sc-gzVnrw kaPVmr</name>
   <tag></tag>
   <elementGuidId>a0d556e0-992e-4ce5-aa9e-e71d9e5db0fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div/div/div/div[2]/div/div[2]/div/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.sc-gzVnrw.kaPVmr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.englishpatient.org/english-patient-files/caa70426-84c2-45ea-a888-e745f694b082.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-gzVnrw kaPVmr</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-iOqSUu kPUIF&quot;]/div[@class=&quot;sc-caSCKo hoPXgy undefined ChessTemplate&quot;]/div[@class=&quot;sc-kjoXOD eUxBJX Right&quot;]/div[@class=&quot;sc-jklikK dDLUFi&quot;]/div[@class=&quot;sc-eerKOB ksFIiR TableDefaultContainer&quot;]/div[@class=&quot;sc-emmjRN jtNoSh container&quot;]/div[@class=&quot;sc-gJWqzi jsepCx TableBody&quot;]/div[@class=&quot;sc-izfUZz dHBlDw&quot;]/div[@class=&quot;sc-kQsIoO iytBnV&quot;]/div[@class=&quot;sc-gPzReC irVTpr&quot;]/div[@class=&quot;sc-jrIrqw gHClob&quot;]/div[@class=&quot;sc-ifAKCX dSelFF BottomUserPanel&quot;]/div[@class=&quot;sc-EHOje elTfnC Left&quot;]/div[@class=&quot;sc-gzVnrw kaPVmr&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div/div[2]/div/div[2]/div/div/div/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/div/div</value>
   </webElementXpaths>
</WebElementEntity>
