<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__fc-icon fc-icon-chevron-left</name>
   <tag></tag>
   <elementGuidId>8b1d7489-2d9e-4476-b7bd-d6d48b8a7aea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='section-to-print']/div/div/div[2]/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.fc-icon.fc-icon-chevron-left</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fc-icon fc-icon-chevron-left</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;section-to-print&quot;)/div[@class=&quot;fc fc-ltr fc-unthemed&quot;]/div[@class=&quot;fc-toolbar fc-header-toolbar&quot;]/div[@class=&quot;fc-center&quot;]/button[@class=&quot;fc-prev-button fc-button fc-button-primary&quot;]/span[@class=&quot;fc-icon fc-icon-chevron-left&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section-to-print']/div/div/div[2]/button/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
   </webElementXpaths>
</WebElementEntity>
