<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_   __-_-src-components-profile-___input_b67287</name>
   <tag></tag>
   <elementGuidId>ab8c98c9-48d9-4b5a-96d0-0b62729cc3bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='layout']/div[2]/div/div[2]/div/form/div[2]/div/div/div[3]/div/div/div/div[2]/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div._-_-src-components-profile-___inputDayPicker__datepickerWrapperOverlay___15Cqw._-_-src-___index__datepicker-wrapper__overlay___3s1Fw</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_-_-src-components-profile-___inputDayPicker__datepickerWrapperOverlay___15Cqw _-_-src-___index__datepicker-wrapper__overlay___3s1Fw</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layout&quot;)/div[@class=&quot;_-_-src-components-componentKit2-___layout__layoutInner___3qSRs _-_-src-___index2__layout__inner___Mts3C undefined&quot;]/div[@class=&quot;_-_-src-components-componentKit2-___layout__grid___3tN4B _-_-src-___index2__grid___2FOUr&quot;]/div[@class=&quot;_-_-src-components-componentKit2-___layout__gridCellLayoutContentPocket34___3K3vW _-_-src-components-componentKit2-___layout__width75___dUSvB _-_-src-___index2__grid__cell___3sCh5&quot;]/div[@class=&quot;_-_-src-components-componentKit2-___layout__layoutWrap___I17Wy _-_-src-components-componentKit2-___layout__layoutWrapSmm___Rc2mr&quot;]/form[1]/div[2]/div[@class=&quot;_-_-src-modules-Mlm-MlmRegistration-___styles__mlmRegistration___2gwxk&quot;]/div[@class=&quot;educationAnWorkInfo&quot;]/div[@class=&quot;_-_-src-components-componentKit2-___addBlock__addBlock___10hJZ&quot;]/div[1]/div[@class=&quot;_-_-src-components-componentKit2-___addBlock__border___75rgj&quot;]/div[1]/div[@class=&quot;_-_-src-modules-Mlm-MlmRegistration-___styles__gridCell33___ZG136 _-_-src-modules-Mlm-MlmRegistration-___styles__width33___3ArS0 _-_-src-___index2__grid__cell___3sCh5&quot;]/div[@class=&quot;_-_-src-modules-Mlm-MlmRegistration-___styles__input___1qi4H _-_-src-___index2__input___20uZl&quot;]/div[@class=&quot;_-_-src-components-profile-___inputDayPicker__datepickerWrapper___QtUr_ _-_-src-___index__datepicker-wrapper___1olVC&quot;]/div[@class=&quot;_-_-src-components-profile-___inputDayPicker__datepickerWrapperOverlay___15Cqw _-_-src-___index__datepicker-wrapper__overlay___3s1Fw&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout']/div[2]/div/div[2]/div/form/div[2]/div/div/div[3]/div/div/div/div[2]/div/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/div/div/div</value>
   </webElementXpaths>
</WebElementEntity>
