<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_2022_react-datepicker</name>
   <tag></tag>
   <elementGuidId>ae6a7b37-cd08-4c26-a1b2-73cbfa2a575c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.react-datepicker__year-read-view--down-arrow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/form/div/div/div[2]/div/div[3]/div[5]/div[2]/div[3]/div[2]/div/div/div[2]/div/div[2]/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-datepicker__year-read-view--down-arrow</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;RouterApp__Wrapper-sc-itp1b8-0 fGnCKq LayoutContainer&quot;]/div[@class=&quot;ChessTemplate__Wrapper-sc-o4z6mm-0 cMIiDp ChessTemplate&quot;]/div[@class=&quot;ChessTemplate__Right-sc-o4z6mm-2 evkQso Right&quot;]/form[1]/div[@class=&quot;TableDefault__Wrapper-sc-t4zu4e-0 gAtJor TableDefaultContainer&quot;]/div[@class=&quot;TableDefault__Container-sc-t4zu4e-2 cWVTNO container&quot;]/div[@class=&quot;TableDefault__TableBody-sc-t4zu4e-9 bErBiJ TableBody&quot;]/div[@class=&quot;UserForm__Container-sc-11tvuqc-6 edNvtS&quot;]/div[@class=&quot;UserForm__CellsContainer-sc-11tvuqc-8 gewAcA&quot;]/div[@class=&quot;UserForm__Cell-sc-11tvuqc-7 eZlHPZ&quot;]/div[@class=&quot;DatePicker__DatePickerWrapper-sc-113g22x-0 fVFsFp&quot;]/div[@class=&quot;react-datepicker__tab-loop&quot;]/div[@class=&quot;react-datepicker-popper&quot;]/div[1]/div[@class=&quot;react-datepicker&quot;]/div[@class=&quot;react-datepicker__month-container&quot;]/div[@class=&quot;react-datepicker__header&quot;]/div[@class=&quot;react-datepicker__header__dropdown react-datepicker__header__dropdown--scroll&quot;]/div[@class=&quot;react-datepicker__year-dropdown-container react-datepicker__year-dropdown-container--scroll&quot;]/div[@class=&quot;react-datepicker__year-read-view&quot;]/span[@class=&quot;react-datepicker__year-read-view--down-arrow&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/form/div/div/div[2]/div/div[3]/div[5]/div[2]/div[3]/div[2]/div/div/div[2]/div/div[2]/div/div/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/span</value>
   </webElementXpaths>
</WebElementEntity>
