<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_13</name>
   <tag></tag>
   <elementGuidId>18a2fed3-a86e-45d7-a61c-7292b03c9d3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div/div[3]/div/div/div[2]/div/div/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TeacherHockeyLinesPlayerCard__Card-sc-1qufjp9-2 lepbXF Card TeacherHockeyLinesPlayerCard</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>13 Булавчук Оскар</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;RouterApp__Wrapper-sc-itp1b8-0 fGnCKq LayoutContainer&quot;]/div[@class=&quot;ChessTemplate__Wrapper-sc-o4z6mm-0 cMIiDp ChessTemplate&quot;]/div[@class=&quot;ChessTemplate__Right-sc-o4z6mm-2 evkQso Right&quot;]/div[@class=&quot;StudentHockeyLinesApp__HockeyLineWrapper-sc-iodqkz-0 efztGw&quot;]/div[@class=&quot;StudentHockeyLinesApp__HockeyLineContentWrapper-sc-iodqkz-2 cXEKuH&quot;]/div[@class=&quot;StudentHockeyLinesApp__HockeyLineContent-sc-iodqkz-4 gMvEkK&quot;]/div[@class=&quot;StudentHockeyLinesApp__LinesTab-sc-iodqkz-30 kiMsxI LinesTab&quot;]/div[@class=&quot;StudentHockeyLinesApp__LinesTabLines-sc-iodqkz-31 jDclnq LinesTabLines&quot;]/div[@class=&quot;StudentHockeyLinesApp__LinesTabLineContainer-sc-iodqkz-32 kAQBXa LinesTabLineContainer&quot;]/div[@class=&quot;StudentHockeyLinesApp__LinesTabLine-sc-iodqkz-33 fAdULx LinesTabLine&quot;]/div[@class=&quot;StudentHockeyLinesApp__LinesTabLineColumn-sc-iodqkz-35 StudentHockeyLinesApp__LinesTabLineColumnWingers-sc-iodqkz-37 gVPTQZ LinesTabLineColumnWingers&quot;]/div[@class=&quot;StudentHockeyLinesApp__TeacherHockeyLinesPlayerCards-sc-iodqkz-36 fVwYzQ TeacherHockeyLinesPlayerCards&quot;]/div[@class=&quot;TeacherHockeyLinesPlayerCard__Card-sc-1qufjp9-2 lepbXF Card TeacherHockeyLinesPlayerCard&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div[3]/div/div/div[2]/div/div/div/div/div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Данила'])[1]/following::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ганин'])[1]/following::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div/div/div/div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '13 Булавчук Оскар' or . = '13 Булавчук Оскар')]</value>
   </webElementXpaths>
</WebElementEntity>
