<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ui__Input-sc-1cni9v4-1 jzzeSa_1</name>
   <tag></tag>
   <elementGuidId>75b8de96-f6a4-4049-ac90-0665112ff73f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'password' and @placeholder = 'Пароль']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Пароль</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui__Input-sc-1cni9v4-1 jzzeSa</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>zz4waxq6</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;RouterApp__Wrapper-sc-itp1b8-0 fGnCKq LayoutContainer&quot;]/div[@class=&quot;BrandedLoginApp__Wrapper-sc-1l8x99f-0 hjlysV&quot;]/div[@class=&quot;BrandedLoginApp__Inner-sc-1l8x99f-3 dMaUdW&quot;]/div[@class=&quot;BrandedLoginApp__LoginPanelPlaceholder-sc-1l8x99f-2 hXlMbH&quot;]/div[@class=&quot;TwoSectionedPanel__Wrapper-sc-z2rqwg-0 hoEqjD&quot;]/div[@class=&quot;TwoSectionedPanel__Right-sc-z2rqwg-2 doBgck&quot;]/div[@class=&quot;BrandedLoginApp__RightContentPlaceholder-sc-1l8x99f-1 itkZkL&quot;]/div[@class=&quot;StyledLoginForm__Wrapper-sc-4j6w6l-0 jIWKYz&quot;]/div[@class=&quot;StyledLoginForm__ContentPlaceholder-sc-4j6w6l-2 kmtXOt&quot;]/div[@class=&quot;StyledLoginForm__Field-sc-4j6w6l-4 gnlZRx&quot;]/input[@class=&quot;ui__Input-sc-1cni9v4-1 jzzeSa&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='zz4waxq6']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div[2]/div/div/div[2]/div[2]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Пароль']</value>
   </webElementXpaths>
</WebElementEntity>
