<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>player 1</name>
   <tag></tag>
   <elementGuidId>a88a0a72-063f-4560-aaf8-184db44c85ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.TeacherHockeyLinesPanel__LinesAvailablePlayerContain-sc-fka3iw-35.flQZHG</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[1]/div/div[2]/div/div[3]/div/div/div[2]/div/div[1]/div/div[2]/div/div/div[1]/div/div[2]/div/div[1]/div/div/div[1]/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TeacherHockeyLinesPanel__LinesAvailablePlayerContain-sc-fka3iw-35 flQZHG</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-tabs-0-panel-0&quot;)/div[@class=&quot;TeacherHockeyLinesPanel__LinesAvailablePlayersContainer-sc-fka3iw-36 kGRttZ&quot;]/div[@class=&quot;TeacherHockeyLinesPanel__LinesAvailablePlayers-sc-fka3iw-30 bubBka&quot;]/div[@class=&quot;TeacherHockeyLinesPanel__BasketPartItem-sc-fka3iw-34 gCWfnD&quot;]/div[@class=&quot;TeacherHockeyLinesPanel__LinesAvailablePlayerContain-sc-fka3iw-35 flQZHG&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-tabs-0-panel-0']/div/div/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div/div/div/div[2]/div/div/div/div/div/div</value>
   </webElementXpaths>
</WebElementEntity>
