<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verif palyer null ln</name>
   <tag></tag>
   <elementGuidId>813b86d6-041a-4012-a092-c8d3f7acd9ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='printme']/div/div[4]/div/div/div/div/div/div/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.TeacherHockeyLinesPlayerEmptyCard__CardPosition-sc-1fb11qi-4.jSIHlU</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TeacherHockeyLinesPlayerEmptyCard__CardPosition-sc-1fb11qi-4 jSIHlU</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>лн</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;printme&quot;)/div[@class=&quot;TeamPart__LinesTab-sc-jkenfl-1 llHIvc LinesTab&quot;]/div[@class=&quot;TeacherHockeyLinesPanel__LinesTabLines-sc-fka3iw-25 fdFDbX LinesTabLines&quot;]/div[@class=&quot;TeacherHockeyLinesPanel__LinesTabLineContainer-sc-fka3iw-26 gExWlq LinesTabLineContainer&quot;]/div[@class=&quot;style__LinesTabLine-sc-1p89q7k-0 lhlsAP LinesTabLine&quot;]/div[@class=&quot;style__LinesTabLineColumn-sc-1p89q7k-3 style__LinesTabLineColumnWingers-sc-1p89q7k-4 cbqkW LinesTabLineColumnWingers&quot;]/div[@class=&quot;style__TeacherHockeyLinesPlayerCards-sc-1p89q7k-2 eEejdB TeacherHockeyLinesPlayerCards&quot;]/div[@class=&quot;TeacherHockeyLinesPlayerEmptyCard__EmptyCard-sc-1fb11qi-1 eIxriQ EmptyCard&quot;]/div[@class=&quot;TeacherHockeyLinesPlayerEmptyCard__EmptyCardContainer-sc-1fb11qi-2 lcKBsB EmptyCardContainer&quot;]/div[@class=&quot;TeacherHockeyLinesPlayerEmptyCard__EmptyCardIconWrapper-sc-1fb11qi-3 iIzzfq EmptyCardIconWrapper&quot;]/p[@class=&quot;TeacherHockeyLinesPlayerEmptyCard__CardPosition-sc-1fb11qi-4 jSIHlU&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='printme']/div/div[4]/div/div/div/div/div/div/div/p</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Добавить в избранное'])[1]/following::p[9]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Очистить состав звеньев'])[1]/following::p[9]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Заикин'])[1]/preceding::p[6]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Андрей'])[1]/preceding::p[6]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='лн']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/div/div/p</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'лн' or . = 'лн')]</value>
   </webElementXpaths>
</WebElementEntity>
