<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_</name>
   <tag></tag>
   <elementGuidId>324f57da-5194-4ca4-977a-fd80456b132c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.BrandedLoginApp__RightContentPlaceholder-sc-1l8x99f-1.itkZkL</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>BrandedLoginApp__RightContentPlaceholder-sc-1l8x99f-1 itkZkL</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ВходВойти</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;RouterApp__Wrapper-sc-itp1b8-0 fGnCKq LayoutContainer&quot;]/div[@class=&quot;BrandedLoginApp__Wrapper-sc-1l8x99f-0 hjlysV&quot;]/div[@class=&quot;BrandedLoginApp__Inner-sc-1l8x99f-3 dMaUdW&quot;]/div[@class=&quot;BrandedLoginApp__LoginPanelPlaceholder-sc-1l8x99f-2 hXlMbH&quot;]/div[@class=&quot;TwoSectionedPanel__Wrapper-sc-z2rqwg-0 hoEqjD&quot;]/div[@class=&quot;TwoSectionedPanel__Right-sc-z2rqwg-2 doBgck&quot;]/div[@class=&quot;BrandedLoginApp__RightContentPlaceholder-sc-1l8x99f-1 itkZkL&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div[2]/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'ВходВойти' or . = 'ВходВойти')]</value>
   </webElementXpaths>
</WebElementEntity>
