<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>edit 4</name>
   <tag></tag>
   <elementGuidId>d467c211-2c98-416d-bce4-759d6649d9ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/form/div[2]/div/div/div/table/tbody/tr[3]/td[2]/div/div[5]/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>EstimationRadioGroup__EstimationRadioButtonDisplay-sc-1f0e7cc-0 ccXJAN</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;RouterApp__Wrapper-sc-itp1b8-0 fGnCKq LayoutContainer&quot;]/div[@class=&quot;ChessTemplate__Wrapper-sc-o4z6mm-0 cMIiDp ChessTemplate&quot;]/div[@class=&quot;ChessTemplate__Right-sc-o4z6mm-2 evkQso Right&quot;]/form[@class=&quot;GameEstimationPanel__Wrapper-sc-1cwndci-0 idYchv&quot;]/div[@class=&quot;GoalTenderTeacherEstimationForm__Wrapper-sc-kta29f-0 joKJgs&quot;]/div[@class=&quot;TableDefault__Wrapper-sc-t4zu4e-0 gAtJor TableDefaultContainer&quot;]/div[@class=&quot;TableDefault__Container-sc-t4zu4e-1 leYvCZ container&quot;]/div[@class=&quot;TableDefault__TableBody-sc-t4zu4e-8 hxVXxi TableBody&quot;]/table[@class=&quot;GoaltenderEstimationItem__TableWrapper-sc-fw7lne-0 czBCBG&quot;]/tbody[@class=&quot;GoaltenderEstimationItem__TableBody-sc-fw7lne-5 ggzeDl&quot;]/tr[@class=&quot;GoaltenderEstimationItem__ParameterTr-sc-fw7lne-4 iYlvnj&quot;]/td[@class=&quot;GoaltenderEstimationItem__ParameterTd-sc-fw7lne-6 lkSSwR&quot;]/div[@class=&quot;RadioGroup&quot;]/div[@class=&quot;EstimationRadioGroup__EstimationRadioButtonLabelContainer-sc-1f0e7cc-1 latSEs&quot;]/label[@class=&quot;EstimationRadioGroup__EstimationRadioButtonLabel-sc-1f0e7cc-2 jQSHRH&quot;]/span[@class=&quot;EstimationRadioGroup__EstimationRadioButtonDisplay-sc-1f0e7cc-0 ccXJAN&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/form/div[2]/div/div/div/table/tbody/tr[3]/td[2]/div/div[5]/label/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Без оценки'])[1]/following::span[12]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Никита Подлягин'])[1]/preceding::span[38]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Без оценки'])[2]/preceding::span[38]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='5']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/label/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '5' or . = '5')]</value>
   </webElementXpaths>
</WebElementEntity>
