<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ _event__estimation-link</name>
   <tag></tag>
   <elementGuidId>e9eb3700-9352-4b90-a59f-846b49873dd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.event__estimation-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='section-to-print']/div/div[2]/div/div/table/tbody/tr[11]/td[6]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/game_estimation/rLDpRSHFH8</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-estimator-name</name>
      <type>Main</type>
      <value>ТЕСТОВАЯ ИГРА - ИГРА ТЕСТОВАЯ </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-event__estimation-link</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;section-to-print&quot;)/div[@class=&quot;fc fc-ltr fc-unthemed&quot;]/div[@class=&quot;fc-view-container&quot;]/div[@class=&quot;fc-view fc-listMonth-view fc-list-view fc-widget-content&quot;]/div[@class=&quot;fc-scroller&quot;]/table[@class=&quot;fc-list-table&quot;]/tbody[1]/tr[@class=&quot;fc-list-item fc-allow-mouse-resize&quot;]/td[@class=&quot;fc-list-item-estimation-button&quot;]/a[@class=&quot;event__estimation-link&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section-to-print']/div/div[2]/div/div/table/tbody/tr[11]/td[6]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/game_estimation/rLDpRSHFH8')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/a</value>
   </webElementXpaths>
</WebElementEntity>
