<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_  _sc-dVhcbM biUGMG TrainerGameEstima_2037e9</name>
   <tag></tag>
   <elementGuidId>7ed8c1b5-57ff-40cf-a1a9-e5c9293bcdc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;root&quot;]/div[1]/div/div[2]/div/div/div[2]/div[1]/div[1]/div/div/div[3]/div[3]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-dVhcbM biUGMG TrainerGameEstimationInput</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-cexcsO cFGwUF&quot;]/div[@class=&quot;sc-kjoXOD bOpiat ChessTemplate&quot;]/div[@class=&quot;sc-TOsTZ fYHaXZ Right&quot;]/div[@class=&quot;sc-erheUI kwiiJu&quot;]/div[@class=&quot;sc-gPEVay cQBXaj&quot;]/div[@class=&quot;sc-erheUI kwiiJu&quot;]/div[1]/div[@class=&quot;sc-bRyDhe ZzvQu&quot;]/div[@class=&quot;sc-hQrNYi eVQIGb&quot;]/div[@class=&quot;sc-hHRaiR ieeemK&quot;]/div[@class=&quot;sc-fsGQkc dOKSjN&quot;]/div[@class=&quot;sc-kQeHGI cLtcrR&quot;]/div[@class=&quot;sc-muxYx eOexJr&quot;]/input[@class=&quot;sc-dVhcbM biUGMG TrainerGameEstimationInput&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div[2]/div/div/div/div/div[3]/div[3]/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/input</value>
   </webElementXpaths>
</WebElementEntity>
