<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ _background-color-white react-datepi_9dfda8</name>
   <tag></tag>
   <elementGuidId>707d55e9-c338-4d54-bf8f-26e01decbe59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@type = 'text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.background-color-white.react-datepicker-ignore-onclickoutside</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value='18:02'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>background-color-white react-datepicker-ignore-onclickoutside</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>18:02</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-cseMdb bhvxyO&quot;]/div[@class=&quot;sc-fAjcbJ eyFHvV undefined ChessTemplate&quot;]/div[@class=&quot;sc-gisBJw lBZmU Right&quot;]/div[@class=&quot;sc-gBSKhj cGrGrd&quot;]/div[@class=&quot;sc-kxYOAa eCCWLR&quot;]/div[@class=&quot;sc-gJWqzi jWffNm Wrapper&quot;]/div[@class=&quot;sc-laTMn ffDYXb ContentPlaceholder&quot;]/div[@class=&quot;sc-lhGUXL kVVoVC&quot;]/div[@class=&quot;sc-fjmCvl zAZSI Wrapper&quot;]/div[@class=&quot;Tab&quot;]/div[@class=&quot;sc-dTdPqK iIYbYs ContentPlaceholder&quot;]/div[@class=&quot;sc-hTQSVH hdVcey&quot;]/div[@class=&quot;popup-container popup-container_theme_alfa-on-white sidebar sidebar_visible sidebar_theme_alfa-on-white AddEventSidebar&quot;]/div[@class=&quot;sidebar__inner&quot;]/div[@class=&quot;sidebar__content&quot;]/div[1]/div[@class=&quot;sc-jbWsrJ wDjBG AwayGameForm&quot;]/div[@class=&quot;sc-ZUflv sc-hPeUyl guzxbe&quot;]/div[@class=&quot;sc-hqGPoI bytzAi halfWidthField&quot;]/div[@class=&quot;react-datepicker-wrapper&quot;]/div[@class=&quot;react-datepicker__input-container&quot;]/input[@class=&quot;background-color-white react-datepicker-ignore-onclickoutside&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value='18:02'])[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div[2]/div[2]/div/div/div[2]/div/div/div[3]/div[2]/div/div/div[2]/div[5]/div[3]/div[2]/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/input</value>
   </webElementXpaths>
</WebElementEntity>
