<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_270500  - 1000  ()-2005</name>
   <tag></tag>
   <elementGuidId>dbbfdcd8-2d26-49be-8c5e-225cfe9e5e8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div/div/div[2]/div/div[2]/div/div/table/tbody/tr[2]/td[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.custom-event-wrapper</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-event-wrapper</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>27ср05:00  - 10:00Игры команды (выездная)Авангард-2005</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-eNhtbY ibnHyQ LayoutContainer&quot;]/div[@class=&quot;sc-dVhcbM hiidKm ChessTemplate&quot;]/div[@class=&quot;sc-fAjcbJ eVflEW Right&quot;]/div[@class=&quot;sc-boSogY dSxlLr&quot;]/div[@class=&quot;sc-ekkqgF dUYUGv mainCalendar&quot;]/div[@class=&quot;mainCalendar__preloaderWrapper&quot;]/div[@class=&quot;fc fc-media-screen fc-direction-ltr fc-theme-standard&quot;]/div[@class=&quot;fc-view-harness fc-view-harness-passive&quot;]/div[@class=&quot;fc-list  fc-list-sticky fc-listDay-view fc-view&quot;]/div[@class=&quot;fc-scroller&quot;]/table[@class=&quot;fc-list-table&quot;]/tbody[1]/tr[@class=&quot;fc-list-event  fc-event fc-event-start fc-event-end fc-event-today fc-event-future&quot;]/td[@class=&quot;fc-list-event-title&quot;]/div[@class=&quot;custom-event-wrapper&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div[2]/div/div[2]/div/div/table/tbody/tr[2]/td[3]/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='среда'])[1]/following::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Месяц'])[1]/following::div[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Редактирование профиля'])[1]/preceding::div[11]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div</value>
   </webElementXpaths>
</WebElementEntity>
