<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>game</name>
   <tag></tag>
   <elementGuidId>95eb6ebc-4ed2-497c-886f-ae0617ec4b25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.fc-timegrid-event.fc-v-event.fc-event.fc-event-start.fc-event-end.fc-event-today.fc-event-future > div.fc-event-main > div.custom-event</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div/div/div[2]/div/div[2]/div/table/tbody/tr[3]/td/div/div/div/div[2]/table/tbody/tr/td[4]/div/div[2]/div/a/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-event</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Игры команды (выездная)автотест - Авангард-2005Оценить игру</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-hAHkbj bvqESJ LayoutContainer&quot;]/div[@class=&quot;sc-dVhcbM hiidKm ChessTemplate&quot;]/div[@class=&quot;sc-fAjcbJ eVflEW Right&quot;]/div[@class=&quot;sc-epYIkJ dCTPJq&quot;]/div[@class=&quot;sc-ekkqgF dUYUGv mainCalendar&quot;]/div[@class=&quot;mainCalendar__preloaderWrapper&quot;]/div[@class=&quot;fc fc-media-screen fc-direction-ltr fc-theme-standard&quot;]/div[@class=&quot;fc-view-harness fc-view-harness-passive&quot;]/div[@class=&quot;fc-timegrid fc-timeGridWeek-view fc-view&quot;]/table[@class=&quot;fc-scrollgrid&quot;]/tbody[1]/tr[@class=&quot;fc-scrollgrid-section fc-scrollgrid-section-body&quot;]/td[1]/div[@class=&quot;fc-scroller-harness&quot;]/div[@class=&quot;fc-scroller&quot;]/div[@class=&quot;fc-timegrid-body&quot;]/div[@class=&quot;fc-timegrid-cols&quot;]/table[1]/tbody[1]/tr[1]/td[@class=&quot;fc-timegrid-col fc-day fc-day-wed fc-day-today&quot;]/div[@class=&quot;fc-timegrid-col-frame&quot;]/div[@class=&quot;fc-timegrid-col-events&quot;]/div[@class=&quot;fc-timegrid-event-harness fc-timegrid-event-harness-inset&quot;]/a[@class=&quot;fc-timegrid-event fc-v-event fc-event fc-event-start fc-event-end fc-event-today fc-event-future&quot;]/div[@class=&quot;fc-event-main&quot;]/div[@class=&quot;custom-event&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-event-name</name>
      <type>Main</type>
      <value>автотест - Авангард-2005</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div[2]/div/div[2]/div/table/tbody/tr[3]/td/div/div/div/div[2]/table/tbody/tr/td[4]/div/div[2]/div/a/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Оценить игру'])[2]/following::div[13]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Оценить игру'])[1]/following::div[16]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Авангард-2005;'])[1]/preceding::div[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div/div[2]/div/a/div/div</value>
   </webElementXpaths>
</WebElementEntity>
