<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>save</name>
   <tag></tag>
   <elementGuidId>637c5856-c9b0-4f44-9144-d2bb752bbca7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.sc-cvbbAY.iaoXyh</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;root&quot;]/div[1]/div/div[2]/div/div/div[2]/form/div/div/div[2]/div/div/form/div[3]/div/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-cvbbAY iaoXyh</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Добавить</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-dKJIhD dqogtp LayoutContainer&quot;]/div[@class=&quot;sc-dVhcbM hiidKm ChessTemplate&quot;]/div[@class=&quot;sc-fAjcbJ eVflEW Right&quot;]/div[@class=&quot;sc-fbkmYA eQIjeO&quot;]/div[@class=&quot;sc-gjcKCj gQuQcP&quot;]/div[@class=&quot;sc-gNmWso gcvQqP&quot;]/div[@class=&quot;sc-eYTUqP gnyNQV&quot;]/div[@class=&quot;sc-bhVptL indiPA&quot;]/div[@class=&quot;sc-bnXvFD iFtDPs Wrapper&quot;]/div[@class=&quot;sc-gJWqzi bTffPK ContentPlaceholder&quot;]/div[@class=&quot;sc-goBNrf hLyLPw&quot;]/div[@class=&quot;sc-gxbSSY laTmnl SchoolLessonsPanel SchoolLessonsPanel_teacher&quot;]/div[1]/div[@class=&quot;sc-klSiHT fQiyMl mainCalendar&quot;]/div[@class=&quot;mainCalendar__preloaderWrapper&quot;]/form[@class=&quot;sc-csSMhA jJOIcF&quot;]/div[@class=&quot;sc-hcmgZB jkUxoD&quot;]/div[@class=&quot;popup-container popup-container_theme_alfa-on-white sidebar sidebar_visible sidebar_theme_alfa-on-white EventModal EventModal_create Sidebar&quot;]/div[@class=&quot;sidebar__inner&quot;]/div[@class=&quot;sidebar__content&quot;]/div[1]/form[@class=&quot;sc-csSMhA jJOIcF&quot;]/div[@class=&quot;sc-jTNJqp gqtCAq BottomPanel&quot;]/div[@class=&quot;sc-fAfrNB iGdqPF Buttons&quot;]/button[@class=&quot;sc-cvbbAY iaoXyh&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div/div/div/div[2]/div[2]/div/div/div/div/div[2]/form/div/div/div[2]/div/div/form/div[2]/div/button[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Закрыть'])[1]/following::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ядыкин Егор'])[1]/following::button[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Редактирование профиля'])[1]/preceding::button[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Добавить']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/button[2]</value>
   </webElementXpaths>
</WebElementEntity>
