<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__icon icon_size_l icon_name_close icon_0f5dee</name>
   <tag></tag>
   <elementGuidId>6c1966cb-bf67-4dfd-94b3-2055f11e81d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div/div/div[2]/form/div/div/div[2]/header/div/button/span/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.icon.icon_size_l.icon_name_close.icon_theme_alfa-on-white</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon icon_size_l icon_name_close icon_theme_alfa-on-white</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-eNhtbY ibnHyQ LayoutContainer&quot;]/div[@class=&quot;sc-dVhcbM hiidKm ChessTemplate&quot;]/div[@class=&quot;sc-fAjcbJ eVflEW Right&quot;]/div[@class=&quot;sc-boSogY dSxlLr&quot;]/div[@class=&quot;sc-ekkqgF dUYUGv mainCalendar&quot;]/div[@class=&quot;mainCalendar__preloaderWrapper&quot;]/form[@class=&quot;sc-bIqbHp cKEeIq&quot;]/div[@class=&quot;sc-eEieub hTufhn&quot;]/div[@class=&quot;popup-container popup-container_theme_alfa-on-white sidebar sidebar_visible sidebar_theme_alfa-on-white EventModal EventModal_create Sidebar&quot;]/div[@class=&quot;sidebar__inner&quot;]/header[@class=&quot;sidebar__header&quot;]/div[@class=&quot;sidebar__closer&quot;]/button[@class=&quot;icon-button icon-button_size_l icon-button_hovered icon-button_theme_alfa-on-white&quot;]/span[@class=&quot;icon-button__content&quot;]/span[@class=&quot;icon-button__text&quot;]/span[@class=&quot;icon icon_size_l icon_name_close icon_theme_alfa-on-white&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div[2]/form/div/div/div[2]/header/div/button/span/span/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div/div/div/div[2]/div[2]/div/div/div/div/div[2]/form/div/div/div[2]/header/div/button/span/span/span</value>
   </webElementXpaths>
</WebElementEntity>
