<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>start_time</name>
   <tag></tag>
   <elementGuidId>c522eb59-52a2-49df-9ee2-89eaa659e162</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.background-color-white.react-datepicker-ignore-onclickoutside</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;root&quot;]/div[1]/div/div[2]/div/div/div[2]/form/div/div/div[2]/div/div/form/div[1]/div[2]/div[2]/div/div[2]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>background-color-white react-datepicker-ignore-onclickoutside</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>10:45</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-dKJIhD dqogtp LayoutContainer&quot;]/div[@class=&quot;sc-dVhcbM hiidKm ChessTemplate&quot;]/div[@class=&quot;sc-fAjcbJ eVflEW Right&quot;]/div[@class=&quot;sc-fbkmYA eQIjeO&quot;]/div[@class=&quot;sc-gjcKCj gQuQcP&quot;]/div[@class=&quot;sc-gNmWso gcvQqP&quot;]/div[@class=&quot;sc-eYTUqP gnyNQV&quot;]/div[@class=&quot;sc-bhVptL indiPA&quot;]/div[@class=&quot;sc-bnXvFD iFtDPs Wrapper&quot;]/div[@class=&quot;sc-gJWqzi bTffPK ContentPlaceholder&quot;]/div[@class=&quot;sc-goBNrf hLyLPw&quot;]/div[@class=&quot;sc-gxbSSY laTmnl SchoolLessonsPanel SchoolLessonsPanel_teacher&quot;]/div[1]/div[@class=&quot;sc-klSiHT fQiyMl mainCalendar&quot;]/div[@class=&quot;mainCalendar__preloaderWrapper&quot;]/form[@class=&quot;sc-csSMhA jJOIcF&quot;]/div[@class=&quot;sc-hcmgZB jkUxoD&quot;]/div[@class=&quot;popup-container popup-container_theme_alfa-on-white sidebar sidebar_visible sidebar_theme_alfa-on-white EventModal EventModal_create Sidebar&quot;]/div[@class=&quot;sidebar__inner&quot;]/div[@class=&quot;sidebar__content&quot;]/div[1]/form[@class=&quot;sc-csSMhA jJOIcF&quot;]/div[@class=&quot;sc-bscRGj kwiFFg&quot;]/div[@class=&quot;sc-hlELIx iNzYnU&quot;]/div[@class=&quot;sc-erOsFi sc-eGXxtx kZNZlS&quot;]/div[@class=&quot;sc-MKjYC gDSAIT&quot;]/div[@class=&quot;react-datepicker-wrapper&quot;]/div[@class=&quot;react-datepicker__input-container&quot;]/input[@class=&quot;background-color-white react-datepicker-ignore-onclickoutside&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='10:45']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div/div/div/div[2]/div[2]/div/div/div/div/div[2]/form/div/div/div[2]/div/div/form/div/div[2]/div[2]/div/div[2]/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/input</value>
   </webElementXpaths>
</WebElementEntity>
