<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tip</name>
   <tag></tag>
   <elementGuidId>36048c1b-2029-4204-8cfe-027398e31a06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-1yd0fai-control > div.css-18eoaig</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Выбрать' or . = 'Выбрать')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;root&quot;]/div[1]/div/div[2]/div/div/div[2]/form/div/div/div[2]/div/div/form/div[1]/div[1]/div/div/div/div/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-18eoaig</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Выбрать</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-dKJIhD dqogtp LayoutContainer&quot;]/div[@class=&quot;sc-dVhcbM hiidKm ChessTemplate&quot;]/div[@class=&quot;sc-fAjcbJ eVflEW Right&quot;]/div[@class=&quot;sc-fbkmYA eQIjeO&quot;]/div[@class=&quot;sc-gjcKCj gQuQcP&quot;]/div[@class=&quot;sc-gNmWso gcvQqP&quot;]/div[@class=&quot;sc-eYTUqP gnyNQV&quot;]/div[@class=&quot;sc-bhVptL indiPA&quot;]/div[@class=&quot;sc-bnXvFD iFtDPs Wrapper&quot;]/div[@class=&quot;sc-gJWqzi bTffPK ContentPlaceholder&quot;]/div[@class=&quot;sc-goBNrf hLyLPw&quot;]/div[@class=&quot;sc-gxbSSY laTmnl SchoolLessonsPanel SchoolLessonsPanel_teacher&quot;]/div[1]/div[@class=&quot;sc-klSiHT fQiyMl mainCalendar&quot;]/div[@class=&quot;mainCalendar__preloaderWrapper&quot;]/form[@class=&quot;sc-csSMhA jJOIcF&quot;]/div[@class=&quot;sc-hcmgZB jkUxoD&quot;]/div[@class=&quot;popup-container popup-container_theme_alfa-on-white sidebar sidebar_visible sidebar_theme_alfa-on-white EventModal EventModal_create Sidebar&quot;]/div[@class=&quot;sidebar__inner&quot;]/div[@class=&quot;sidebar__content&quot;]/div[1]/form[@class=&quot;sc-csSMhA jJOIcF&quot;]/div[@class=&quot;sc-bscRGj kwiFFg&quot;]/div[@class=&quot;sc-hlELIx iNzYnU&quot;]/div[@class=&quot;sc-erOsFi sc-eetwQk dWfZtk&quot;]/div[@class=&quot;sc-eXNvrr gRVCNH SelectContainer&quot;]/div[@class=&quot;css-1pcexqc-container Select&quot;]/div[@class=&quot;css-1yd0fai-control&quot;]/div[@class=&quot;css-18eoaig&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div/div/div/div[2]/div[2]/div/div/div/div/div[2]/form/div/div/div[2]/div/div/form/div/div/div/div/div/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Тип мероприятия'])[1]/following::div[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Добавить мероприятие'])[2]/following::div[7]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Воспитательное мероприятие'])[1]/preceding::div[7]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div/div/div</value>
   </webElementXpaths>
</WebElementEntity>
