<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas_1</name>
   <tag></tag>
   <elementGuidId>0a9883ac-923a-471a-a3ef-a2ff9989ebf7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div/div[3]/div/div/div/div[2]/div/div[2]/div/div/div/canvas[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-zr-dom-id</name>
      <type>Main</type>
      <value>zr_10</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>3070</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>600</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-iOqSUu kPUIF&quot;]/div[@class=&quot;sc-caSCKo hoPXgy undefined ChessTemplate&quot;]/div[@class=&quot;sc-kjoXOD eUxBJX Right&quot;]/div[@class=&quot;sc-jWNpPo iMzVDn&quot;]/div[@class=&quot;sc-dQRrkI gBPwes&quot;]/div[@class=&quot;sc-kJhCQv lkpwZz&quot;]/div[@class=&quot;sc-eerKOB ksFIiR TableDefaultContainer&quot;]/div[@class=&quot;sc-emmjRN jtNoSh container&quot;]/div[@class=&quot;sc-gJWqzi jsepCx TableBody&quot;]/div[@class=&quot;sc-jjbLbC eyJmYM&quot;]/div[@class=&quot;sc-ctDIWD bMVyHt&quot;]/div[1]/div[1]/div[1]/canvas[2]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div[3]/div/div/div/div[2]/div/div[2]/div/div/div/canvas[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas[2]</value>
   </webElementXpaths>
</WebElementEntity>
