<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_math</name>
   <tag></tag>
   <elementGuidId>3c756791-fef3-4573-8111-1b016543d1da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='simple-tabpanel-5']/div/div/div/div/div[2]/div/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/div[3]/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.MuiDataGrid-columnHeader.MuiDataGrid-columnHeader--alignCenter.MuiDataGrid-columnHeader--sortable > div.MuiDataGrid-columnHeaderDraggableContainer > div.MuiDataGrid-columnHeaderTitleContainer > div.MuiDataGrid-columnHeaderTitle.css-cc8tf1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiDataGrid-columnHeaderTitle css-cc8tf1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Матчи</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;simple-tabpanel-5&quot;)/div[@class=&quot;MuiBox-root css-0&quot;]/div[@class=&quot;personal-file-view-stats__Wrapper-sc-t9ao4b-0 hpGfqq&quot;]/div[@class=&quot;style__PersonalFilePreloaderContainer-sc-12qvwmx-11 frUNZD&quot;]/div[@class=&quot;style__PersonalFileTab-sc-12qvwmx-0 style__PersonalFileTabWithoutMargins-sc-12qvwmx-1 bxXYcJ&quot;]/div[@class=&quot;PlayerStatsReportTable__Wrapper-sc-1a31mbg-0 bTnJwo PlayerStatsReportTableWrapper&quot;]/div[@class=&quot;TableDefaultContainer__Wrapper-sc-1exdyki-0 jAJxLA TableDefaultContainer PlayerStatsReportTable&quot;]/div[@class=&quot;TableDefaultContainer__Container-sc-1exdyki-1 ZLAcr container&quot;]/div[@class=&quot;TableDefaultContainer__TableBody-sc-1exdyki-8 fCKPyM TableBody&quot;]/div[@class=&quot;PlayerStatsReportTable__TableContent-sc-1a31mbg-1 XwlDL&quot;]/div[@class=&quot;Table__Wrapper-sc-6695ot-0 bRTkwu&quot;]/div[@class=&quot;Table__Container-sc-6695ot-1 eKMALr&quot;]/div[@class=&quot;ScrollbarsCustom trackXVisible&quot;]/div[@class=&quot;ScrollbarsCustom-Wrapper&quot;]/div[@class=&quot;ScrollbarsCustom-Scroller&quot;]/div[@class=&quot;ScrollbarsCustom-Content&quot;]/div[@class=&quot;MuiDataGrid-root MuiDataGrid-autoHeight css-svmzg5&quot;]/div[@class=&quot;MuiDataGrid-main css-1fm09i6&quot;]/div[@class=&quot;MuiDataGrid-columnHeaders css-qw65j7&quot;]/div[@class=&quot;MuiDataGrid-columnHeadersInner MuiDataGrid-columnHeadersInner--scrollable css-um056b&quot;]/div[@class=&quot;MuiDataGrid-columnHeader MuiDataGrid-columnHeader--alignCenter MuiDataGrid-columnHeader--sortable&quot;]/div[@class=&quot;MuiDataGrid-columnHeaderDraggableContainer&quot;]/div[@class=&quot;MuiDataGrid-columnHeaderTitleContainer&quot;]/div[@class=&quot;MuiDataGrid-columnHeaderTitle css-cc8tf1&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='simple-tabpanel-5']/div/div/div/div/div[2]/div/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/div[3]/div/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ранг'])[1]/following::div[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Игрок'])[1]/following::div[10]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Игр. время'])[1]/preceding::div[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Бр. в створ'])[1]/preceding::div[9]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Матчи']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/div/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Матчи' or . = 'Матчи')]</value>
   </webElementXpaths>
</WebElementEntity>
