<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ 5.  110</name>
   <tag></tag>
   <elementGuidId>21e5dc06-ab11-4dd7-99bc-1db839135af5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='list']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div._-_-src-modules-Training-components-ListExercises-___styles__group___3QK_E</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_-_-src-modules-Training-components-ListExercises-___styles__group___3QK_E</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>День 5. Сессия 110 видео</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layout&quot;)/div[@class=&quot;_-_-src-components-componentKit2-___layout__layoutInner___3qSRs _-_-src-___index2__layout__inner___Mts3C undefined&quot;]/div[@class=&quot;_-_-src-components-componentKit2-___layout__grid___3tN4B _-_-src-___index2__grid___2FOUr&quot;]/div[@class=&quot;_-_-src-components-componentKit2-___layout__gridCellLayoutContentPocket34___3K3vW _-_-src-components-componentKit2-___layout__width75___dUSvB _-_-src-___index2__grid__cell___3sCh5&quot;]/div[@class=&quot;_-_-src-components-componentKit2-___layout__layoutWrap___I17Wy _-_-src-components-componentKit2-___layout__layoutWrapSmm___Rc2mr&quot;]/div[1]/div[@class=&quot;_-_-src-modules-Training-containers-TrainingPlaylist-___styles__content___SPW9b&quot;]/div[@class=&quot;_-_-src-modules-Training-containers-TrainingPlaylist-___styles__content__text___3q7Kq&quot;]/div[@class=&quot;_-_-src-modules-Training-containers-TrainingPlaylist-___styles__info___19V_t&quot;]/div[@class=&quot;_-_-src-modules-Training-containers-TrainingPlaylist-___styles__top___2nCyN&quot;]/div[@class=&quot;tabs&quot;]/div[@class=&quot;_-_-src-modules-Training-containers-TrainingPlaylist-___styles__tab__text___3_fEI&quot;]/div[@class=&quot;_-_-src-modules-Training-containers-TrainingPlaylist-___styles__playlist__container___2v_me&quot;]/div[@id=&quot;list&quot;]/div[1]/div[@class=&quot;_-_-src-modules-Training-components-ListExercises-___styles__group___3QK_E&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list']/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='День 5. Сессия 1']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div</value>
   </webElementXpaths>
</WebElementEntity>
