<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>48626eda-a2ef-47c4-a0c2-2301c34fd4dc</elementGuidId>
   <imagePath>Screenshots/Targets/Page_/a_.png</imagePath>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;root&quot;)/div[@class=&quot;sc-cseMdb bhvxyO&quot;]/div[@class=&quot;sc-fAjcbJ eyFHvV undefined ChessTemplate&quot;]/div[@class=&quot;sc-gisBJw lBZmU Right&quot;]/div[@class=&quot;sc-epsdGI cxKXMa&quot;]/div[@class=&quot;sc-fjmCvl zAZSI Wrapper&quot;]/div[@class=&quot;Tab&quot;]/div[@class=&quot;sc-dTdPqK iIYbYs ContentPlaceholder&quot;]/div[1]/div[@class=&quot;sc-fQJGqW fBUnSE&quot;]/div[@class=&quot;sc-eilVRo dNmLwC TableDefaultContainer&quot;]/div[@class=&quot;sc-eerKOB esDKJN container&quot;]/div[@class=&quot;sc-emmjRN cRZYqn Headline&quot;]/div[@class=&quot;sc-bnXvFD flvbTp HeadlineTitleContainer&quot;]/div[@class=&quot;sc-cpmLhU jiyxFt HeadlineTitle&quot;]/div[@class=&quot;sc-gFaPwZ kHWxi HeadLineTitleContent&quot;]/a[@class=&quot;sc-kWYWtc bBGMHY&quot;][count(. | //*[@href = 'https://stars-back-stage.hawk.ru:8080/export/physical-testing/individual/20-21/9dQ8c5KUuz' and (text() = 'Экспорт' or . = 'Экспорт')]) = count(//*[@href = 'https://stars-back-stage.hawk.ru:8080/export/physical-testing/individual/20-21/9dQ8c5KUuz' and (text() = 'Экспорт' or . = 'Экспорт')])]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Page_/a_.png</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.sc-kWYWtc.bBGMHY</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div/div/div[2]/div/div/div[2]/div/div/div/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://stars-back-stage.hawk.ru:8080/export/physical-testing/individual/20-21/9dQ8c5KUuz</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-kWYWtc bBGMHY</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Экспорт</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-cseMdb bhvxyO&quot;]/div[@class=&quot;sc-fAjcbJ eyFHvV undefined ChessTemplate&quot;]/div[@class=&quot;sc-gisBJw lBZmU Right&quot;]/div[@class=&quot;sc-epsdGI cxKXMa&quot;]/div[@class=&quot;sc-fjmCvl zAZSI Wrapper&quot;]/div[@class=&quot;Tab&quot;]/div[@class=&quot;sc-dTdPqK iIYbYs ContentPlaceholder&quot;]/div[1]/div[@class=&quot;sc-fQJGqW fBUnSE&quot;]/div[@class=&quot;sc-eilVRo dNmLwC TableDefaultContainer&quot;]/div[@class=&quot;sc-eerKOB esDKJN container&quot;]/div[@class=&quot;sc-emmjRN cRZYqn Headline&quot;]/div[@class=&quot;sc-bnXvFD flvbTp HeadlineTitleContainer&quot;]/div[@class=&quot;sc-cpmLhU jiyxFt HeadlineTitle&quot;]/div[@class=&quot;sc-gFaPwZ kHWxi HeadLineTitleContent&quot;]/a[@class=&quot;sc-kWYWtc bBGMHY&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div[2]/div/div/div[2]/div/div/div/div/div/div/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Экспорт')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Алхимов Сергей'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Игрок'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Редактирование профиля'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Экспорт']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://stars-back-stage.hawk.ru:8080/export/physical-testing/individual/20-21/9dQ8c5KUuz')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/a</value>
   </webElementXpaths>
</WebElementEntity>
