<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_email</name>
   <tag></tag>
   <elementGuidId>28b6ecc0-822a-4474-b8a0-87880dddc962</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;email&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_-_-src-components-componentKit2-___inputProfile__inputField___1nHsc _-_-src-___index__input__field___1GlLk _-_-src-components-profile-___loginValidationForm__inputCustom___1AwY5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;_-_-src-components-profile-___loginValidationForm__entry___2iNuZ&quot;]/div[@class=&quot;_-_-src-components-profile-___loginValidationForm__layoutEntry___2dG0g _-_-src-___index__layout___30At8 _-_-src-___index__layout--entry___LKA_D&quot;]/div[@class=&quot;_-_-src-components-profile-___loginValidationForm__entryMin___3MTfN _-_-src-___index__entry___1GyIE _-_-src-___index__entry--min___1eTAx&quot;]/div[@class=&quot;_-_-src-components-profile-___loginValidationForm__entryInner___2tgNK _-_-src-___index__entry__inner___2v65j&quot;]/form[@class=&quot;_-_-src-components-profile-___loginValidationForm__entryBox___QfNCP _-_-src-___index__entry__box___rUP3e&quot;]/div[@class=&quot;_-_-src-components-profile-___loginValidationForm__input___-TXLA _-_-src-___index2__input___20uZl&quot;]/div[@class=&quot;_-_-src-components-componentKit2-___inputProfile__inputBox___3Yop2 _-_-src-___index__input___1sucD _-_-src-___index__input--box___2L6Ex&quot;]/input[@class=&quot;_-_-src-components-componentKit2-___inputProfile__inputField___1nHsc _-_-src-___index__input__field___1GlLk _-_-src-components-profile-___loginValidationForm__inputCustom___1AwY5&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='email']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div/form/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
   </webElementXpaths>
</WebElementEntity>
