<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_</name>
   <tag></tag>
   <elementGuidId>1ae930e7-1623-445a-b6a7-2b1d2bd35b86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button._-_-src-components-profile-___loginValidationForm__buttonSecondaryWide___3SPnW._-_-src-___index__btn___8I487._-_-src-___index__btn--secondary___3B1B2._-_-src-___index__wide___3fiu0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_-_-src-components-profile-___loginValidationForm__buttonSecondaryWide___3SPnW _-_-src-___index__btn___8I487 _-_-src-___index__btn--secondary___3B1B2 _-_-src-___index__wide___3fiu0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Войти</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;_-_-src-components-profile-___loginValidationForm__entry___2iNuZ&quot;]/div[@class=&quot;_-_-src-components-profile-___loginValidationForm__layoutEntry___2dG0g _-_-src-___index__layout___30At8 _-_-src-___index__layout--entry___LKA_D&quot;]/div[@class=&quot;_-_-src-components-profile-___loginValidationForm__entryMin___3MTfN _-_-src-___index__entry___1GyIE _-_-src-___index__entry--min___1eTAx&quot;]/div[@class=&quot;_-_-src-components-profile-___loginValidationForm__entryInner___2tgNK _-_-src-___index__entry__inner___2v65j&quot;]/form[@class=&quot;_-_-src-components-profile-___loginValidationForm__entryBox___QfNCP _-_-src-___index__entry__box___rUP3e&quot;]/button[@class=&quot;_-_-src-components-profile-___loginValidationForm__buttonSecondaryWide___3SPnW _-_-src-___index__btn___8I487 _-_-src-___index__btn--secondary___3B1B2 _-_-src-___index__wide___3fiu0&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div/form/button</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Забыли пароль?'])[1]/following::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Пароль'])[1]/following::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Регистрация'])[1]/preceding::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Русский'])[1]/preceding::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
   </webElementXpaths>
</WebElementEntity>
