<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>opis</name>
   <tag></tag>
   <elementGuidId>f27a62f3-3a12-4290-bb0b-d0aba91b3149</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='layout']/div[3]/div/div[2]/div/div/div[2]/div/div/div/div/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div._-_-src-components-common-TabsNav-___styles__tabNavItem___XDxgM._-_-src-components-common-TabsNav-___styles__show___xZOI8</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_-_-src-components-common-TabsNav-___styles__tabNavItem___XDxgM _-_-src-components-common-TabsNav-___styles__show___xZOI8</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Описание</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layout&quot;)/div[@class=&quot;_-_-src-components-componentKit2-___layout__layoutInner___3qSRs _-_-src-___index2__layout__inner___Mts3C undefined&quot;]/div[@class=&quot;_-_-src-components-componentKit2-___layout__grid___3tN4B _-_-src-___index2__grid___2FOUr&quot;]/div[@class=&quot;_-_-src-components-componentKit2-___layout__gridCellLayoutContentPocket34___3K3vW _-_-src-components-componentKit2-___layout__width75___dUSvB _-_-src-___index2__grid__cell___3sCh5&quot;]/div[@class=&quot;_-_-src-components-componentKit2-___layout__layoutWrap___I17Wy _-_-src-components-componentKit2-___layout__layoutWrapSmm___Rc2mr&quot;]/div[1]/div[@class=&quot;_-_-src-modules-Training-containers-TrainingPlaylist-___styles__content___SPW9b&quot;]/div[@class=&quot;_-_-src-modules-Training-containers-TrainingPlaylist-___styles__content__text___3q7Kq&quot;]/div[@class=&quot;_-_-src-modules-Training-containers-TrainingPlaylist-___styles__info___19V_t&quot;]/div[@class=&quot;_-_-src-modules-Training-containers-TrainingPlaylist-___styles__top___2nCyN&quot;]/div[@class=&quot;tabs&quot;]/div[@class=&quot;_-_-src-components-common-TabsNav-___styles__tabNavList___1-9Yq _-_-src-components-common-TabsNav-___styles__tabWebinars___3C4hQ _-_-src-components-common-TabsNav-___styles__tabStandard___2G527 _-_-src-components-common-TabsNav-___styles__tabNavListStandart___lEIei&quot;]/div[@class=&quot;_-_-src-components-common-TabsNav-___styles__tabNavItemWrap___1Ag4q _-_-src-components-common-TabsNav-___styles__tabNavItemWrapStandart___1BVJL&quot;]/div[@class=&quot;_-_-src-components-common-TabsNav-___styles__tabNavItem___XDxgM _-_-src-components-common-TabsNav-___styles__show___xZOI8&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout']/div[3]/div/div[2]/div/div/div[2]/div/div/div/div/div/div/div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Куплен'])[1]/following::div[10]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Активировать'])[1]/following::div[11]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Заметки'])[1]/preceding::div[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Normal'])[2]/preceding::div[25]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Описание']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/div/div/div/div[2]</value>
   </webElementXpaths>
</WebElementEntity>
