<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ _sc-hmQHRE fyqSUx</name>
   <tag></tag>
   <elementGuidId>698c4e55-99df-4689-8a38-8e6c974313c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.sc-hmQHRE.fyqSUx</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div/div[2]/div[2]/div/div/div/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.englishpatient.org/english-patient-files/adf0910f-932a-46e0-92e6-53d752e09b7c.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>player avatar</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-hmQHRE fyqSUx</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-JPfNM iXfuSc&quot;]/div[@class=&quot;sc-caSCKo hoPXgy ChessTemplate&quot;]/div[@class=&quot;sc-kjoXOD eUxBJX Right&quot;]/div[@class=&quot;sc-hydxCu fnodST&quot;]/div[@class=&quot;sc-cHRTLU duciRW&quot;]/div[@class=&quot;sc-wTvpg HNzZs&quot;]/div[@class=&quot;sc-idSxJg sc-hrRoet dTYRzq&quot;]/div[@class=&quot;sc-iYscQK dlGeVs PlayersRatingListItemTop PlayersRatingListItemTopFirstPlace&quot;]/div[@class=&quot;sc-iruUXe cLHiJJ&quot;]/div[@class=&quot;sc-gPKJgF csTIXD&quot;]/div[@class=&quot;sc-bjbPDc bWiOix PlayersRatingListItemContentPartContainer&quot;]/div[@class=&quot;sc-ZxTAX jugQwL PlayersRatingListItemPlayerImgContainer&quot;]/div[@class=&quot;sc-hmQHRE fyqSUx&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div[2]/div[2]/div/div/div/div/div/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/div/div/div</value>
   </webElementXpaths>
</WebElementEntity>
