<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__sc-hmQHRE fQpMfg</name>
   <tag></tag>
   <elementGuidId>5a1f4909-c826-4ecc-8365-b15f4422b46b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.sc-hmQHRE.fQpMfg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div/div[2]/div[2]/div[2]/div[2]/div/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.englishpatient.org/english-patient-files/bf5936c1-cfd3-486e-a4e2-ae66bb1b9d1a.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>player avatar</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-hmQHRE fQpMfg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-JPfNM iXfuSc&quot;]/div[@class=&quot;sc-caSCKo hoPXgy ChessTemplate&quot;]/div[@class=&quot;sc-kjoXOD eUxBJX Right&quot;]/div[@class=&quot;sc-hydxCu fnodST&quot;]/div[@class=&quot;sc-cHRTLU duciRW&quot;]/div[@class=&quot;sc-wTvpg HNzZs&quot;]/div[@class=&quot;sc-idSxJg sc-hrRoet dTYRzq&quot;]/div[@class=&quot;sc-iYscQK dlGeVs PlayersRatingListItemTop PlayersRatingListItemTopSecondPlace&quot;]/div[@class=&quot;sc-iruUXe cLHiJJ&quot;]/div[@class=&quot;sc-gPKJgF csTIXD&quot;]/div[@class=&quot;sc-bjbPDc bWiOix PlayersRatingListItemContentPartContainer&quot;]/div[@class=&quot;sc-ZxTAX jugQwL PlayersRatingListItemPlayerImgContainer&quot;]/div[@class=&quot;sc-hmQHRE fQpMfg&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div[2]/div[2]/div[2]/div[2]/div/div/div/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div[2]/div/div/div/div/div</value>
   </webElementXpaths>
</WebElementEntity>
