<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_TestAdmintest.ru</name>
   <tag></tag>
   <elementGuidId>b591944d-53ea-40cb-9af3-0bec50f3ca6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.MySidebar__OptionsList-sc-1x14ih2-6.NcYwH.OptionsList</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MySidebar__OptionsList-sc-1x14ih2-6 NcYwH OptionsList</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ГлавнаяОтчетыУправлениеРасписаниеНаправлениеДокументыРекомендации по ОФПТрансляцииСпортШколыКомандыИгрокиТренерыРейтинг игроковАдминистратор ТестовыйTestAdmin@test.ruАдминистраторВыйти</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;RouterApp__Wrapper-sc-itp1b8-0 fGnCKq LayoutContainer&quot;]/div[@class=&quot;ChessTemplate__Wrapper-sc-o4z6mm-0 cMIiDp ChessTemplate&quot;]/div[@class=&quot;ChessTemplate__Left-sc-o4z6mm-1 hgViGl Left&quot;]/div[@class=&quot;MySidebar__Wrapper-sc-1x14ih2-0 Rihzz&quot;]/div[@class=&quot;MySidebar__OptionsList-sc-1x14ih2-6 NcYwH OptionsList&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='≡'])[1]/following::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'ГлавнаяОтчетыУправлениеРасписаниеНаправлениеДокументыРекомендации по ОФПТрансляцииСпортШколыКомандыИгрокиТренерыРейтинг игроковАдминистратор ТестовыйTestAdmin@test.ruАдминистраторВыйти' or . = 'ГлавнаяОтчетыУправлениеРасписаниеНаправлениеДокументыРекомендации по ОФПТрансляцииСпортШколыКомандыИгрокиТренерыРейтинг игроковАдминистратор ТестовыйTestAdmin@test.ruАдминистраторВыйти')]</value>
   </webElementXpaths>
</WebElementEntity>
