<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__phone</name>
   <tag></tag>
   <elementGuidId>fa949636-2194-46a3-8b75-5903fffaf111</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;phone&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='phone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Телефон</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phone</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>my_phone</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;RouterApp__Wrapper-sc-itp1b8-0 fGnCKq LayoutContainer&quot;]/div[@class=&quot;ChessTemplate__Wrapper-sc-o4z6mm-0 cMIiDp ChessTemplate&quot;]/div[@class=&quot;ChessTemplate__Right-sc-o4z6mm-2 evkQso Right&quot;]/div[@class=&quot;personal-file__Wrapper-sc-26pu1p-0 fSVweO&quot;]/div[@class=&quot;TableDefaultContainer__Wrapper-sc-1exdyki-0 jAJxLA TableDefaultContainer&quot;]/div[@class=&quot;TableDefaultContainer__Container-sc-1exdyki-1 ZLAcr container&quot;]/div[@class=&quot;TableDefaultContainer__TableBody-sc-1exdyki-8 fCKPyM TableBody&quot;]/div[@class=&quot;style__PersonalFilePreloaderContainer-sc-12qvwmx-11 frUNZD&quot;]/form[@class=&quot;personal-file-edit__PersonalFileEditForm-sc-1yp80dx-0 kSIfYS&quot;]/div[@class=&quot;personal-file-edit__PersonalFileEditContent-sc-1yp80dx-1 cYIThJ&quot;]/div[@class=&quot;personal-file-edit__PersonalFileEditContentContainer-sc-1yp80dx-2 dOfvFv&quot;]/div[@class=&quot;personal-file-edit__PersonalFileEditContentBlock-sc-1yp80dx-5 bWuDfN&quot;]/div[@class=&quot;personal-file-edit__PersonalFileEditContentBlockRow-sc-1yp80dx-6 fHWGvd&quot;]/div[@class=&quot;personal-file-edit__PersonalFileEditContentBlockColumn-sc-1yp80dx-8 ktNvPy&quot;]/input[@class=&quot;my_phone&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='phone']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[2]/div/div/div[2]/div/form/div/div[3]/div[2]/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Телефон' and @name = 'phone']</value>
   </webElementXpaths>
</WebElementEntity>
