<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>player3</name>
   <tag></tag>
   <elementGuidId>c2b9e7b4-b71f-4253-9f11-bfe09c77d1bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[1]/div/div[2]/div/div[3]/div/div/div[2]/div/div[1]/div/div[2]/div/div/div[1]/div/div[2]/div/div[1]/div/div/div[3]/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
