<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mail</name>
   <tag></tag>
   <elementGuidId>acf0b930-0ba6-4927-87d2-c593f82b7ae2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.sc-fYiAbW.kfFRqY</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@type = 'email' and @placeholder = 'Ваш E-Mail']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ваш E-Mail</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-fYiAbW kfFRqY</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>levashev.ps@hc-avangard.com</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-bHUQhK fGGFmZ LayoutContainer&quot;]/div[@class=&quot;sc-dliRfk iNROGf&quot;]/div[@class=&quot;sc-iqzUVk cUzvFX&quot;]/div[@class=&quot;sc-qrIAp kxniIo&quot;]/div[@class=&quot;sc-cQFLBn kzkBhc&quot;]/div[@class=&quot;sc-daURTG luVmd&quot;]/div[@class=&quot;sc-kLIISr epGlVh&quot;]/div[@class=&quot;sc-eerKOB kZdUzR&quot;]/div[@class=&quot;sc-cpmLhU HpvsV&quot;]/div[@class=&quot;sc-bnXvFD NzhvH&quot;]/input[@class=&quot;sc-fYiAbW kfFRqY&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='levashev.ps@hc-avangard.com']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div[2]/div/div/div[2]/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
   </webElementXpaths>
</WebElementEntity>
