<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_1</name>
   <tag></tag>
   <elementGuidId>b55c172a-f9ba-4ad7-bd30-b2155c356361</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.EstimationRadioGroup__EstimationRadioButtonDisplay-sc-1f0e7cc-0.ccXJAN</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[1]/div/div[2]/div/form/div[1]/table/tbody/tr[1]/td[2]/div/div[1]/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>EstimationRadioGroup__EstimationRadioButtonDisplay-sc-1f0e7cc-0 ccXJAN</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;RouterApp__Wrapper-sc-itp1b8-0 fGnCKq LayoutContainer&quot;]/div[@class=&quot;ChessTemplate__Wrapper-sc-o4z6mm-0 cMIiDp ChessTemplate&quot;]/div[@class=&quot;ChessTemplate__Right-sc-o4z6mm-2 evkQso Right&quot;]/div[@class=&quot;SkillsEstimationPanel__Wrapper-sc-1tgrngp-0 eOdETR&quot;]/form[@class=&quot;SkillsEstimationForm__EstimationForm-sc-14j86w1-1 bqzDXi toFind&quot;]/div[@class=&quot;style__TableBlockContainer-sc-151ipr8-0 ipFORJ&quot;]/table[@class=&quot;style__TableBlock-sc-151ipr8-2 dPZrZE&quot;]/tbody[@class=&quot;style__TableBlockBody-sc-151ipr8-6 lkHVIn&quot;]/tr[@class=&quot;style__TableBlockRow-sc-151ipr8-5 fvraKO&quot;]/td[@class=&quot;style__TableBlockColumn-sc-151ipr8-8 fenOUT&quot;]/div[@class=&quot;RadioGroup&quot;]/div[@class=&quot;EstimationRadioGroup__EstimationRadioButtonLabelContainer-sc-1f0e7cc-1 latSEs&quot;]/label[@class=&quot;EstimationRadioGroup__EstimationRadioButtonLabel-sc-1f0e7cc-2 jQSHRH&quot;]/span[@class=&quot;EstimationRadioGroup__EstimationRadioButtonDisplay-sc-1f0e7cc-0 ccXJAN&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/form/div/table/tbody/tr/td[2]/div/div/label/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Фокус развития'])[1]/following::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='превосходно/блестяще'])[1]/following::span[10]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Навыки'])[2]/preceding::span[66]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '1' or . = '1')]</value>
   </webElementXpaths>
</WebElementEntity>
